### ISSUE TITLE
Animation Speed

### ISSUE THREAD

**Issue by Amir-Latif** [jeremyrajan/nice-react-ticker#19]
Cannot change the animation speed

I used the following

`<Ticker isNewsTicker={true} slideSpeed={6000}>`
and in the dev tools it is unchanged 15s

**Comment by jeremyrajan** [comment]
Thanks for raising this. I have added support for `slideSpeed` in https://github.com/jeremyrajan/nice-react-ticker/releases/tag/v2.1.0. Please update and let me know, if it works :)

cc @Amir-Latif
